//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasPorPagar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Pago_Proveedor
    {
        public int Id_Solicitud { get; set; }
        public int Num_Documento { get; set; }
        public string Num_Factura_Pagar { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Monto { get; set; }
        public string Estado { get; set; }
    
        public virtual Documentos_Pagar Documentos_Pagar { get; set; }
    }
}
